apiVersion: v1
kind: Service
metadata:
  name: student-app-service
  namespace: student-app
  labels:
    app: student-app
spec:
  type: NodePort
  selector:
    app: student-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
